name: Airflow CI / CD Pipeline

on:
  pull_request:
    paths:
      - "services/airflow/**"

env:
  ASRTO_CLI_VERSION: "v1.36.0"

jobs:
  airflow-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            services/airflow/

      - name: Install Astro CLI
        run: curl -sSL install.astronomer.io | sudo bash -s -- ${{ env.ASRTO_CLI_VERSION }}

      - name: Run Tests
        run: astro dev pytest
