name: Dagster CI / CD Pipeline

on:
  pull_request:
    paths:
      - "services/dagster/**"

env:
  UV_VERSION: "0.9.5"
  PYTHON_VERSION: "3.13"

jobs:
  dagster-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            services/dagster/**
            docker/**
            Makefile
          sparse-checkout-cone-mode: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION}}
          enable-cache: true
          prune-cache: false
          working-directory: services/dagster

      - name: Start Services
        run: make start-postgres

      - name: Wait for Postgres
        run: |
          timeout 30 bash -c 'until docker exec postgres pg_isready -U postgres; do sleep 1; done'

      - name: Run Tests
        working-directory: services/dagster
        run: uv run pytest

      - name: Shutdown Services
        if: always()
        run: make stop-postgres
