name: Django CI / CD Pipeline

on:
  pull_request:
    paths:
      - "services/django/**"

env:
  UV_VERSION: "0.9.5"
  PYTHON_VERSION: "3.13"

jobs:
  django-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            services/django/**
            docker/**
            Makefile
          sparse-checkout-cone-mode: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION}}
          enable-cache: true
          prune-cache: false
          working-directory: services/django

      - name: Start Services
        run: make start-postgres

      - name: Run Test Suite
        working-directory: services/django
        run: uv run pytest

      - name: Shutdown Services
        if: always()
        run: make stop-postgres
