name: dbt CI / CD Pipeline

on:
  pull_request:
    paths:
      - "services/dbt/**"

env:
  UV_VERSION: "0.9.5"
  PYTHON_VERSION: "3.13"

jobs:
  dbt-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            services/dbt/**
            docker/**
            Makefile
          sparse-checkout-cone-mode: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION}}
          enable-cache: true
          prune-cache: false
          working-directory: services/dbt

      - name: Start Services
        run: make start-postgres

      - name: Install dbt Dependencies
        working-directory: services/dbt
        run: uv run dbt deps --profiles-dir ./profiles --profile local

      - name: Run dbt Tests
        working-directory: services/dbt
        run: uv run dbt build --profiles-dir ./profiles --profile local

      - name: Shutdown Services
        if: always()
        run: make stop-postgres
