name: Experiments CI / CD Pipeline

on:
  pull_request:
    paths:
      - "services/experiments/**"

env:
  UV_VERSION: "0.8.13"
  PYTHON_VERSION: "3.13"

jobs:
  experiments-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            services/experiments/**
            docker/**
            Makefile
          sparse-checkout-cone-mode: false
          # needed to checkout only a single file

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION}}
          enable-cache: true
          prune-cache: false
          working-directory: services/experiments

      - name: Run experiments Tests
        working-directory: services/experiments
        run: uv run pytest
